# 模考题解析

---

## 单选题

### 1.5.

1.5 字符串格式化是量化投资策略编写过程中常用的方法，那么以下哪种代码可以用来实现浮点数格式化（）？  
A.  %c  
B.  %d  
C.  %f  
D.  %s  

参考答案：C

#### 1.5.1. 知识点

%c表示格式化字符及ASCII码

In [1]:
print('%c' % 70)

F


In [2]:
print('%c' % 66)

B


In [ ]:
print('%c' % 'a')

In [ ]:
print('%c' % 'A')

%d表示格式化整数

In [3]:
print('%d' % '65')

TypeError: %d format: a number is required, not str

In [4]:
print('%d' % 65)

65


In [ ]:
print('%d' % 6.6)

%f表示格式化浮点数

In [5]:
print('%.2f' % 1.23879)

1.24


In [6]:
print('%.2f' % '1.23879')

TypeError: must be real number, not str

%s表示格式化字符串

In [ ]:
print('%s' % 'abc')

In [ ]:
print('%s' % '2.33')

In [ ]:
print('%s' % 2.33)

%e用科学计数法格式化浮点数

In [ ]:
print('%e' % 3100000)

In [ ]:
print('%e' % 0.000032)

In [ ]:
print('%e' % '310000')

#### 1.5.2. 知识拓展

%格式化字符串和.format格式化字符串

In [1]:
'output: %s, %f' %('apple', 1.65)

'output: apple, 1.650000'

In [3]:
'output: {1}, {0}'.format('apple', 1.65)

'output: 1.65, apple'

字符串常用方法

1.str.capitalize() 把字符串的第一个字符大写

In [4]:
'python'.capitalize()

'Python'

In [5]:
a = 'Python'

In [ ]:
a.

In [ ]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".



In [6]:
help(a.count)

Help on built-in function count:

count(...) method of builtins.str instance
    S.count(sub[, start[, end]]) -> int
    
    Return the number of non-overlapping occurrences of substring sub in
    string S[start:end].  Optional arguments start and end are
    interpreted as in slice notation.



2.str.count(sub[, start[, end]])返回s在str里面出现的次数

In [7]:
'anaconda'.count('a')

3

In [ ]:
'anaconda'.count('a', 1)

In [9]:
'anaconda'.count('a', 1, -2)

1

3.str.find(sub[, start[, end]])检测s是否包含在str中，start和end指定查找的范围，返回值为sub在str中起始位置的索引，没有找到情况返回-1

In [10]:
help(str.find)

Help on method_descriptor:

find(...)
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.



In [13]:
code = '300020'

In [15]:
help(code.startswith)

Help on built-in function startswith:

startswith(...) method of builtins.str instance
    S.startswith(prefix[, start[, end]]) -> bool
    
    Return True if S starts with the specified prefix, False otherwise.
    With optional start, test S beginning at that position.
    With optional end, stop comparing S at that position.
    prefix can also be a tuple of strings to try.



In [17]:
code.startswith('6')

False

In [12]:
'anaconda'.find('x')

-1

### 1.7
1.7 当横线处填入（）时，代码打印输出的结果是列表中所有的深交所上市的股票代码？（注意：上交所代码以6开头，深交所代码以0或3开头）
```
for stock_code in ['002003', '600015', '300001', '002300']:
    if stock_code.startswith('6'):
        ____
    print(stock_code)
    
A. raise
B. continue
C. pass
D. break
```
参考答案：B

#### 1.7.1 知识点

break终止当前循环

In [18]:
for stock_code in ['002003', '600015', '300001', '002300']:
    if stock_code.startswith('6'):
        break
    print(stock_code)

002003


continue中断当前循环，直接进入下一个循环

In [19]:
for stock_code in ['002003', '600015', '300001', '002300']:
    if stock_code.startswith('6'):
        continue
    print(stock_code)

002003
300001
002300


pass 保持语法结构完整，不做任何操作，常用在函数和方法中作为占位语句

In [20]:
for stock_code in ['002003', '600015', '300001', '002300']:
    if stock_code.startswith('6'):
        pass
    print(stock_code)

002003
600015
300001
002300


raise用于触发异常，出现异常后，后续代码不会继续操作。

In [21]:
for stock_code in ['002003', '600015', '300001', '002300']:
    if stock_code.startswith('6'):
        raise
    print(stock_code)

002003


RuntimeError: No active exception to reraise

### 1.8 
李明，AQF，某量化基金经理，他在进行策略研究时需要从DataFrame数据类型stock_base_data中提取2018-01-03至2018-01-05（含01-05）时间段中的股票PE、CLOSE数据，该DataFrame如下，则李明提取数据时可以使用的代码为（）？

![image.png](attachment:image.png)

A.  stock_base_data.iloc['2018-01-03':'2018-01-05', ['PE', 'CLOSE']]  
B.  stock_base_data.loc['2018-01-03':'2018-01-05', ['PE', 'CLOSE']]  
C.  stock_base_data.loc[['PE', 'CLOSE'], '2018-01-03':'2018-01-05']  
D.  stock_base_data.iloc[2:4, ['PE', 'CLOSE']]  

参考答案：B

#### 1.8.1. 知识点

In [22]:
# 如何创建DataFrame或者Series
import pandas as pd
stock_base_data = pd.DataFrame(
    [[1.5, 10, 0.05, 35],
     [1.5, 10, 0.05, 36],
     [1.5, 10, 0.05, 34],
     [1.4, 10, -0.10, 32],
     [1.4, 10, -0.10, 33],
     [1.4, 12, -0.10, 30],
     [1.4, 12, -0.10, 29]],
    index=pd.date_range('2018-01-01', periods=7),
    columns=['PB', 'PE', 'ROE', 'CLOSE']
)
stock_base_data

PB  PE   ROE  CLOSE
2018-01-01  1.5  10  0.05     35
2018-01-02  1.5  10  0.05     36
2018-01-03  1.5  10  0.05     34
2018-01-04  1.4  10 -0.10     32
2018-01-05  1.4  10 -0.10     33
2018-01-06  1.4  12 -0.10     30
2018-01-07  1.4  12 -0.10     29

loc标签切片

In [23]:
# 选择单一行
stock_base_data.loc['2018-01-02']

PB        1.50
PE       10.00
ROE       0.05
CLOSE    36.00
Name: 2018-01-02 00:00:00, dtype: float64

In [24]:
# 选择不连续列
stock_base_data.loc[:, ['PE', 'CLOSE']]

PE  CLOSE
2018-01-01  10     35
2018-01-02  10     36
2018-01-03  10     34
2018-01-04  10     32
2018-01-05  10     33
2018-01-06  12     30
2018-01-07  12     29

In [25]:
# 选择不连续列
stock_base_data.loc[:, 'PE':'CLOSE']

PE   ROE  CLOSE
2018-01-01  10  0.05     35
2018-01-02  10  0.05     36
2018-01-03  10  0.05     34
2018-01-04  10 -0.10     32
2018-01-05  10 -0.10     33
2018-01-06  12 -0.10     30
2018-01-07  12 -0.10     29

In [26]:
# 对不同行列进行选择
stock_base_data.loc['2018-01-02':'2018-01-05', ['PE', 'CLOSE']]

PE  CLOSE
2018-01-02  10     36
2018-01-03  10     34
2018-01-04  10     32
2018-01-05  10     33

iloc索引切片

In [27]:
# 选择单一行
stock_base_data.iloc[3]

PB        1.4
PE       10.0
ROE      -0.1
CLOSE    32.0
Name: 2018-01-04 00:00:00, dtype: float64

In [28]:
# 选择不连续的列
stock_base_data.iloc[:, [1,3]]

PE  CLOSE
2018-01-01  10     35
2018-01-02  10     36
2018-01-03  10     34
2018-01-04  10     32
2018-01-05  10     33
2018-01-06  12     30
2018-01-07  12     29

In [29]:
# 同事对行列进行选择
stock_base_data.iloc[1:4, 1:3]

PE   ROE
2018-01-02  10  0.05
2018-01-03  10  0.05
2018-01-04  10 -0.10

#### 1.8.2. 知识点拓展

In [30]:
import pandas as pd
stock_base_data = pd.DataFrame(
    [[1.5, 10, 0.05, 35],
     [1.5, 10, 0.05, 36],
     [1.5, 10, 0.05, 34],
     [1.4, 10, -0.10, 32],
     [1.4, 10, -0.10, 33],
     [1.4, -12, -0.10, 30],
     [1.4, -12, -0.10, 29]],
    index=pd.date_range('2018-01-01', periods=7),
    columns=['PB', 'PE', 'ROE', 'CLOSE']
)
stock_base_data

PB  PE   ROE  CLOSE
2018-01-01  1.5  10  0.05     35
2018-01-02  1.5  10  0.05     36
2018-01-03  1.5  10  0.05     34
2018-01-04  1.4  10 -0.10     32
2018-01-05  1.4  10 -0.10     33
2018-01-06  1.4 -12 -0.10     30
2018-01-07  1.4 -12 -0.10     29

In [31]:
stock_base_data[stock_base_data['PE']<0]

PB  PE  ROE  CLOSE
2018-01-06  1.4 -12 -0.1     30
2018-01-07  1.4 -12 -0.1     29

In [32]:
stock_base_data.loc[stock_base_data['PE']<0, 'PE']

2018-01-06   -12
2018-01-07   -12
Freq: D, Name: PE, dtype: int64

In [33]:
# 将所有PE小于0的PE数据赋值为1000
stock_base_data.loc[stock_base_data['PE']<0, 'PE'] = 1000
stock_base_data

PB    PE   ROE  CLOSE
2018-01-01  1.5    10  0.05     35
2018-01-02  1.5    10  0.05     36
2018-01-03  1.5    10  0.05     34
2018-01-04  1.4    10 -0.10     32
2018-01-05  1.4    10 -0.10     33
2018-01-06  1.4  1000 -0.10     30
2018-01-07  1.4  1000 -0.10     29

In [35]:
# 将所有小于0的数据都转化为相反数
stock_base_data[stock_base_data<0] = -stock_base_data
stock_base_data

PB    PE   ROE  CLOSE
2018-01-01  1.5    10  0.05     35
2018-01-02  1.5    10  0.05     36
2018-01-03  1.5    10  0.05     34
2018-01-04  1.4    10  0.10     32
2018-01-05  1.4    10  0.10     33
2018-01-06  1.4  1000  0.10     30
2018-01-07  1.4  1000  0.10     29

In [37]:
import pandas as pd
stock_base_data = pd.DataFrame(
    [[1.5, 10, 0.05, 35],
     [1.5, 10, 0.05, 36],
     [1.5, 10, 0.05, 34],
     [1.4, 10, -0.10, 32],
     [1.4, 10, -0.10, 33],
     [1.4, -12, -0.10, 30],
     [1.4, -12, -0.10, 29]],
    index=pd.date_range('2018-01-01', periods=7),
    columns=['PB', 'PE', 'ROE', 'CLOSE']
)
stock_base_data

PB  PE   ROE  CLOSE
2018-01-01  1.5  10  0.05     35
2018-01-02  1.5  10  0.05     36
2018-01-03  1.5  10  0.05     34
2018-01-04  1.4  10 -0.10     32
2018-01-05  1.4  10 -0.10     33
2018-01-06  1.4 -12 -0.10     30
2018-01-07  1.4 -12 -0.10     29

In [38]:
# 根据已有数据做判别，在原数据表中加入一列新数据'new_columns'
stock_base_data.loc[stock_base_data['PE']<0, 'new_column'] = 0
stock_base_data

PB  PE   ROE  CLOSE  new_column
2018-01-01  1.5  10  0.05     35         NaN
2018-01-02  1.5  10  0.05     36         NaN
2018-01-03  1.5  10  0.05     34         NaN
2018-01-04  1.4  10 -0.10     32         NaN
2018-01-05  1.4  10 -0.10     33         NaN
2018-01-06  1.4 -12 -0.10     30         0.0
2018-01-07  1.4 -12 -0.10     29         0.0

### 1.9
李明，AQF，某量化基金经理，想要评估长期持有的某只股票在过去三天的总体表现。已知该股票在过去三个交易日的日收益率为0.02, 0.05, 0.06，李明编写了如下代码：
```
import pandas as pd
equity_return = pd.Series([0.02, 0.05, 0.06])
```
请问以下哪行代码可正确计算该股票在过去三个交易日的累计收益率（）？  
A.  equity_return.sum()  
B.  equity_return.mean()  
C.  (equity_return+1).cumprod()[2]-1  
D.  equity_return.ptp()  

参考答案：C

In [39]:
import pandas as pd
equity_return = pd.Series([0.02, 0.05, 0.06])

In [40]:
equity_return

0    0.02
1    0.05
2    0.06
dtype: float64

In [41]:
# sum求和
equity_return.sum()

0.13

In [42]:
# mean求均值
equity_return.mean()

0.043333333333333335

In [43]:
# ptp求极差
equity_return.ptp()

0.039999999999999994

In [45]:
# 答案
(equity_return+1).cumprod()[2]-1

0.13526000000000016

In [46]:
(equity_return+1).cumprod()

0    1.02000
1    1.07100
2    1.13526
dtype: float64

In [ ]:
equity_return.unique  

In [44]:
(1+0.02) * (1+0.05) * (1+0.06) - 1

0.13526000000000016

### 1.13
李明，AQF，某量化基金经理，正在使用Ndarray数据结构储存最近10日的股票收盘价数据并命名为close_data，如果李明现在想取出最后五天的收盘价数据，则使用的切片代码为（）？  
A. close_data[::-5]  
B. close_data[-5:]  
C. close_data[6:]  
D. close_data[5:9]  

参考答案：B

In [47]:
import numpy as np
close_data = np.array([0,1,2,3,4,5,6,7,8,9])

In [48]:
close_data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# 选项A
close_data[::-5]

array([9, 4])

In [51]:
# 选项B
close_data[-5:]

array([5, 6, 7, 8, 9])

In [52]:
# 选项C
close_data[6:]

array([6, 7, 8, 9])

In [53]:
# 选项D
close_data[5:9]

array([5, 6, 7, 8])

#### 1.13.1 知识点

In [54]:
data = np.array([0,1,2,3,4,5,6,7])

In [55]:
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [56]:
data[:]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
data[::2]

array([0, 2, 4, 6])

In [58]:
data[1:4]                     # 前闭后开；

array([1, 2, 3])

In [59]:
data[1:4:2]

array([1, 3])

In [60]:
data[-4:]

array([4, 5, 6, 7])

### 1.14.
李明，AQF，某量化基金经理，正在使用Series储存某只股票日频的交易量数据并命名为volume_data，行index为日期，交易量部分数据如下图。现希望计算每月的交易量之和，则使用的代码为（）？

![image.png](attachment:image.png)

A. volume_data.resample('m').sum()  
B. volume_data.groupby('m').sum()  
C. volume_data.groupby('m').prod()  
D. volume_data.resample('m').prod()  

参考答案：A

In [61]:
import pandas as pd
volume_data = pd.Series(
    [100, 120, 310, 240, 130, 420, 350],
    index=pd.date_range('2018-01-28', periods=7)
)
volume_data

2018-01-28    100
2018-01-29    120
2018-01-30    310
2018-01-31    240
2018-02-01    130
2018-02-02    420
2018-02-03    350
Freq: D, dtype: int64

In [62]:
# 选项A
volume_data.resample('m').sum()

2018-01-31    770
2018-02-28    900
Freq: M, dtype: int64

In [63]:
# 选项B
volume_data.groupby('m').sum()

KeyError: 'm'

In [ ]:
# 选项C
volume_data.groupby('m').prod()

In [64]:
# 选项D
volume_data.resample('m').prod()

2018-01-31    892800000
2018-02-28     19110000
Freq: M, dtype: int64

#### 1.14.1. 知识点

In [65]:
import pandas as pd
volume_data = pd.Series(
    [100, 120, 310, 240, 130, 420, 350, np.nan],
    index=pd.date_range('2018-01-28', periods=8)
)
volume_data

2018-01-28    100.0
2018-01-29    120.0
2018-01-30    310.0
2018-01-31    240.0
2018-02-01    130.0
2018-02-02    420.0
2018-02-03    350.0
2018-02-04      NaN
Freq: D, dtype: float64

In [80]:
volume_data.resample('6H').ffill()

2018-01-28 00:00:00    100.0
2018-01-28 06:00:00    100.0
2018-01-28 12:00:00    100.0
2018-01-28 18:00:00    100.0
2018-01-29 00:00:00    120.0
2018-01-29 06:00:00    120.0
2018-01-29 12:00:00    120.0
2018-01-29 18:00:00    120.0
2018-01-30 00:00:00    310.0
2018-01-30 06:00:00    310.0
2018-01-30 12:00:00    310.0
2018-01-30 18:00:00    310.0
2018-01-31 00:00:00    240.0
2018-01-31 06:00:00    240.0
2018-01-31 12:00:00    240.0
2018-01-31 18:00:00    240.0
2018-02-01 00:00:00    130.0
2018-02-01 06:00:00    130.0
2018-02-01 12:00:00    130.0
2018-02-01 18:00:00    130.0
2018-02-02 00:00:00    420.0
2018-02-02 06:00:00    420.0
2018-02-02 12:00:00    420.0
2018-02-02 18:00:00    420.0
2018-02-03 00:00:00    350.0
2018-02-03 06:00:00    350.0
2018-02-03 12:00:00    350.0
2018-02-03 18:00:00    350.0
2018-02-04 00:00:00      NaN
Freq: 6H, dtype: float64

In [69]:
volume_data.resample('M').min()

2018-01-31    100.0
2018-02-28    130.0
Freq: M, dtype: float64

In [70]:
resampler = volume_data.resample('M')

In [71]:
# .count()方法
resampler.count()

2018-01-31    4
2018-02-28    3
Freq: M, dtype: int64

In [72]:
# .max（）方法
resampler.max()

2018-01-31    310.0
2018-02-28    420.0
Freq: M, dtype: float64

In [73]:
# .ohlc()方法
resampler.ohlc()

open   high    low  close
2018-01-31  100.0  310.0  100.0  240.0
2018-02-28  130.0  420.0  130.0  350.0

举例

In [77]:
import pandas as pd
import numpy as np
# 创建用于resample采样的数据
data = pd.Series(
    np.random.randn(100),
    index=pd.date_range('2018-01-01', periods=100)
)
data.tail()

2018-04-06   -0.724183
2018-04-07    0.019045
2018-04-08    0.011991
2018-04-09    1.132562
2018-04-10   -0.584432
Freq: D, dtype: float64

In [75]:
data.resample('m').sum()

2018-01-31    2.476667
2018-02-28    0.109279
2018-03-31    2.876295
2018-04-30   -3.883892
Freq: M, dtype: float64

In [76]:
data.resample('m').ohlc()

open      high       low     close
2018-01-31  1.086751  1.682886 -1.459154  0.044985
2018-02-28 -0.474206  2.211698 -1.865982 -0.542759
2018-03-31 -0.770066  1.812070 -1.776884 -0.336839
2018-04-30 -1.419800  1.167751 -2.104876 -0.088321

### 1.15. 
李明，AQF，某量化基金经理，正在编写策略回测代码，按惯例导入Numpy模块后读取数据的代码如下：
```
pe_data = np.array([10,15,30])
pe = pe_data[3]
```

则上述代码运行时，报告错误的类型与产生错误的原因为（）？  
A. IndexError, 代码索引超出范围  
B. ImportError, 未导入相应模块  
C. SyntaxError, 代码语法错误  
D. KeyError, 字典的键不存在  

参考答案：A

In [ ]:
pe_data = np.array([10,15,30])
pe = pe_data[3]

#### 1.15.1. 知识点

IndexError（序列中没有此索引时）


In [ ]:
# 可以从help文档中看到对IndexError的描述
help(IndexError)

In [ ]:
list_ = [1, 2, 3, 4]
list_[5]

ImportError（导入不存在模块或从模块中无法找到该名称）


In [ ]:
help(ImportError)

In [ ]:
from pandas import no_exist_object    

In [ ]:
SyntaxError（无效语法）


In [ ]:
help(SyntaxError)

In [ ]:
# 未加for循环后的':'号
for i in range(3)
    print(i)

KeyError（映射的键无法找到）

In [ ]:
help(KeyError)

In [ ]:
dict_ = {'a':1}
dict_['b']

### 1.16. 
列表（List）是量化交易策略中一种常见的数据类型，关于列表的说法中错误的是（）？  
A.  List是不可变对象  
B.  List是有序数据类型  
C.  使用List时，下标可以是负数  
D.  List可以存放任意类型的元素  

参考答案：A

#### 1.16.1. 知识点

列表访问与切片

In [1]:
list_ = [0,1,2,3,4,5,6,7]

In [2]:
list_[5]

5

In [3]:
list_[-5]

3

In [4]:
list_[3:6]

[3, 4, 5]

In [5]:
list_[:10:3]

[0, 3, 6]

#### 1.16.2. 知识拓展


In [6]:
list_ = [0,1,2,3,4,5,6,7]

列表相关函数

In [7]:
# 返回列表长度
len(list_)

8

In [8]:
# 返回列表元素最大值
max(list_)

7

In [9]:
# 将序列转化为列表
list((1,2,3,4))

[1, 2, 3, 4]

列表方法

In [18]:
list_ = [0,1,2,3,4,5,6,7]

In [12]:
# .append()方法：在列表末尾添加元素
list_.append([0,1,2])
list_

[0, 1, 2, 3, 4, 5, 6, 7, 0, [0, 1, 2]]

In [13]:
list_.extend([0,1,2])

In [14]:
list_

[0, 1, 2, 3, 4, 5, 6, 7, 0, [0, 1, 2], 0, 1, 2]

In [15]:
# .count()方法：统计某元素在列表中出现的次数
list_.count(0)

3

In [16]:
# .reverse()方法：倒序排列列表元素，直接修改原列表，没有返回值
list_.reverse()
list_

[2, 1, 0, [0, 1, 2], 0, 7, 6, 5, 4, 3, 2, 1, 0]

In [19]:
# .sort()方法：排序原列表，直接修改原列表，没有返回值
list_.sort()
list_

[0, 1, 2, 3, 4, 5, 6, 7]

In [20]:
help(list_.pop)        # 有返回值；

Help on built-in function pop:

pop(...) method of builtins.list instance
    L.pop([index]) -> item -- remove and return item at index (default last).
    Raises IndexError if list is empty or index is out of range.



### 1.17.
在研究量化策略时，各只股票缩写以字符串形式保存在一个list中，如：close_data = ['aaPL', 'Ibm', 'GM']，由于数据质量问题，该组股票名称大小写不统一，现需要将股票缩写调整为大写，则使用的字符串方法是（）？  
A. str.isdigit()  
B. str.upper()  
C. str.lower()  
D. str.capitalize()  

参考答案：B

In [21]:
# 选项A
'aaPL'.isdigit()

False

In [22]:
# 选项B
'aaPL'.upper()

'AAPL'

In [23]:
# 选项C
'aaPL'.lower()

'aapl'

In [24]:
# 选项D
'aaPL'.capitalize()

'Aapl'

#### 1.17.1. 知识拓展

.isdigit方法：判断字符串是否全部为十进制数字

In [25]:
'12323'.isdigit()

True

In [26]:
# 含字母
'11212a'.isdigit()

False

In [27]:
a = '11212a'

In [28]:
a.isalnum()

True

In [29]:
# 含标点
'12121.121212'.isdigit()

False

.isspace()方法：判断字符串是否为空格

In [30]:
'    '.isspace()

True

In [31]:
'abcd ABCD'.isspace()

False

In [32]:
a = '  11212a  '

In [33]:
a

'  11212a  '

In [34]:
a.lstrip()

'11212a  '

In [35]:
a.rstrip()

'  11212a'

In [36]:
a.strip()

'11212a'

In [ ]:
a.

### 1.19. 
当try语句中没有出现异常，以下一定不会执行的语句是（）？  
A.  try  
B.  except  
C.  finally  
D.  else  

参考答案：B

In [37]:
# 没有异常发生
try:
    print('try')
except IndexError:
    print('IndexError')
else:
    print('else')
finally:
    print('finally')

try
else
finally


In [38]:
# 有IndexError发生
try:
    print('try')
    list_ = [1,2,3,4]
    sub = list_[10]
except IndexError:
    print('IndexError')
else:
    print('else')
finally:
    print('finally')

try
IndexError
finally


### 1.20.
下列哪个代码是进行除法求余数的运算符（）？  
A. /  
B. //  
C. %  
D. divmod(a,b)  

参考答案：C

In [39]:
# 除法运算符
7/4

1.75

In [40]:
# 除法后取整
7//4

1

In [41]:
# 除法后取余数
7%4

3

In [42]:
# 函数，返回商和余数的元组
divmod(7,4)

(1, 3)

#### 1.20.2. 知识拓展

比较运算符

In [43]:
3 != 3

False

In [44]:
4 >= 3

True

身份运算符

In [45]:
# 内存是否指向同一地址
3 is 3

True

赋值运算符

In [46]:
a = 3
a += 3
a

6

逻辑运算符

In [47]:
True and True

True

In [48]:
True and False

False

成员运算符

In [49]:
'a' in 'abc'

True